// <auto-generated />
using System;
using AdwRating.Data.Mssql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdwRating.Data.Mssql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdwRating.Domain.Entities.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Organization")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CallName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedCallName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegisteredName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SizeCategory")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SizeCategoryOverride")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.DogAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AliasType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CanonicalDogId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalDogId");

                    b.HasIndex("AliasName", "AliasType")
                        .IsUnique();

                    b.ToTable("DogAliases");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.Handler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("NormalizedName", "Country")
                        .IsUnique();

                    b.ToTable("Handlers");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.HandlerAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CanonicalHandlerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AliasName")
                        .IsUnique();

                    b.HasIndex("CanonicalHandlerId");

                    b.ToTable("HandlerAliases");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.ImportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<string>("Errors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewDogsCount")
                        .HasColumnType("int");

                    b.Property<int>("NewHandlersCount")
                        .HasColumnType("int");

                    b.Property<int>("NewTeamsCount")
                        .HasColumnType("int");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Warnings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("ImportLogs");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.RatingConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("ChampionTopPercent")
                        .HasColumnType("real");

                    b.Property<int>("CountryTopN")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("DisplayBase")
                        .HasColumnType("real");

                    b.Property<float>("DisplayScale")
                        .HasColumnType("real");

                    b.Property<float>("EliteTopPercent")
                        .HasColumnType("real");

                    b.Property<float>("ExpertTopPercent")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LiveWindowDays")
                        .HasColumnType("int");

                    b.Property<float>("MajorEventWeight")
                        .HasColumnType("real");

                    b.Property<int>("MinFieldSize")
                        .HasColumnType("int");

                    b.Property<int>("MinRunsForLiveRanking")
                        .HasColumnType("int");

                    b.Property<int>("MinTeamsForCountryRanking")
                        .HasColumnType("int");

                    b.Property<float>("Mu0")
                        .HasColumnType("real");

                    b.Property<float>("NormTargetMean")
                        .HasColumnType("real");

                    b.Property<float>("NormTargetStd")
                        .HasColumnType("real");

                    b.Property<float>("PodiumBoostBase")
                        .HasColumnType("real");

                    b.Property<float>("PodiumBoostRange")
                        .HasColumnType("real");

                    b.Property<float>("PodiumBoostTarget")
                        .HasColumnType("real");

                    b.Property<float>("ProvisionalSigmaThreshold")
                        .HasColumnType("real");

                    b.Property<float>("RatingSigmaMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("Sigma0")
                        .HasColumnType("real");

                    b.Property<float>("SigmaDecay")
                        .HasColumnType("real");

                    b.Property<float>("SigmaMin")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("RatingConfigurations");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.RatingSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<float>("Mu")
                        .HasColumnType("real");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("RunResultId")
                        .HasColumnType("int");

                    b.Property<float>("Sigma")
                        .HasColumnType("real");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("RunResultId");

                    b.HasIndex("TeamId", "RunResultId")
                        .IsUnique();

                    b.ToTable("RatingSnapshots");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.Run", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<float?>("CourseLength")
                        .HasColumnType("real");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsTeamRound")
                        .HasColumnType("bit");

                    b.Property<string>("Judge")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<float?>("Mct")
                        .HasColumnType("real");

                    b.Property<string>("OriginalSizeCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoundKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RunNumber")
                        .HasColumnType("int");

                    b.Property<float?>("Sct")
                        .HasColumnType("real");

                    b.Property<string>("SizeCategory")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "RoundKey")
                        .IsUnique();

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.RunResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Eliminated")
                        .HasColumnType("bit");

                    b.Property<int?>("Faults")
                        .HasColumnType("int");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<int?>("Refusals")
                        .HasColumnType("int");

                    b.Property<int>("RunId")
                        .HasColumnType("int");

                    b.Property<float?>("Speed")
                        .HasColumnType("real");

                    b.Property<int?>("StartNo")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<float?>("Time")
                        .HasColumnType("real");

                    b.Property<float?>("TimeFaults")
                        .HasColumnType("real");

                    b.Property<float?>("TotalFaults")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("RunId", "TeamId")
                        .IsUnique();

                    b.ToTable("RunResults");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DogId")
                        .HasColumnType("int");

                    b.Property<int>("FinishedRunCount")
                        .HasColumnType("int");

                    b.Property<int>("HandlerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProvisional")
                        .HasColumnType("bit");

                    b.Property<float>("Mu")
                        .HasColumnType("real");

                    b.Property<float>("PeakRating")
                        .HasColumnType("real");

                    b.Property<float>("PrevMu")
                        .HasColumnType("real");

                    b.Property<float>("PrevRating")
                        .HasColumnType("real");

                    b.Property<float>("PrevSigma")
                        .HasColumnType("real");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("RunCount")
                        .HasColumnType("int");

                    b.Property<float>("Sigma")
                        .HasColumnType("real");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TierLabel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Top3RunCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("HandlerId", "DogId")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.DogAlias", b =>
                {
                    b.HasOne("AdwRating.Domain.Entities.Dog", "CanonicalDog")
                        .WithMany()
                        .HasForeignKey("CanonicalDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalDog");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.HandlerAlias", b =>
                {
                    b.HasOne("AdwRating.Domain.Entities.Handler", "CanonicalHandler")
                        .WithMany()
                        .HasForeignKey("CanonicalHandlerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalHandler");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.ImportLog", b =>
                {
                    b.HasOne("AdwRating.Domain.Entities.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.RatingSnapshot", b =>
                {
                    b.HasOne("AdwRating.Domain.Entities.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdwRating.Domain.Entities.RunResult", "RunResult")
                        .WithMany()
                        .HasForeignKey("RunResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdwRating.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("RunResult");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.Run", b =>
                {
                    b.HasOne("AdwRating.Domain.Entities.Competition", "Competition")
                        .WithMany("Runs")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.RunResult", b =>
                {
                    b.HasOne("AdwRating.Domain.Entities.Run", "Run")
                        .WithMany("RunResults")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdwRating.Domain.Entities.Team", "Team")
                        .WithMany("RunResults")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.Team", b =>
                {
                    b.HasOne("AdwRating.Domain.Entities.Dog", "Dog")
                        .WithMany("Teams")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdwRating.Domain.Entities.Handler", "Handler")
                        .WithMany("Teams")
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("Handler");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.Competition", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.Dog", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.Handler", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.Run", b =>
                {
                    b.Navigation("RunResults");
                });

            modelBuilder.Entity("AdwRating.Domain.Entities.Team", b =>
                {
                    b.Navigation("RunResults");
                });
#pragma warning restore 612, 618
        }
    }
}
